language: node_js
node_js:
  - 10

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./frontend
  - docker tag udagram-frontend stanvolcere/udagram-frontend:latest
  - docker --version # print the version for logging
  - docker build -t udagram-users ./users
  - docker tag udagram-users stanvolcere/udagram-users:latest
  - docker --version # print the version for logging
  - docker build -t udagram-feed ./feed
  - docker tag udagram-feed stanvolcere/udagram-feed:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push stanvolcere/udagram-frontend
  - docker push stanvolcere/udagram-users
  - docker push stanvolcere/udagram-feed